---
- name: Разворачиваем веб-приложение
  hosts: your_remote_server
  become: yes

  roles:
    - nginx
    - php
    - mysql

  tasks:
    - name: Копируем файл Docker Compose на сервер
      copy:
        src: ./docker-compose.yml
        dest: /path/to/docker-compose/docker-compose.yml
        remote_src: yes
      become: yes

    - name: Запуск Docker Compose
      command: docker-compose up -d
      become: yes
      
